### ISSUE TITLE
Windows installation problems (reuse this issue for all windows problems)

### ISSUE THREAD

**Issue by huanceng** [radareorg/r2ghidra#192]
W64 release of `6.0.4` is missing. 

Then I try to load `r2ghidra 6.0.0` in `r2 6.0.0`, but it fails.

<img width="472" height="99" alt="Image" src="https://github.com/user-attachments/assets/96e8fc28-d344-4b80-a1e8-bca6d1f78758" />

Can you please offer the loadable W64 release of `6.0.4`? Thanks a lot.

**Comment by satk0** [comment]
Hi @huanceng, I would love to. I plan to dualboot Windows on my pc to solve most of the win issues for r2g (and play league of legends someday, ehhh). 
So I will try my very best to solve it.

**Comment by huanceng** [comment]
@trufae 
1. the [install batch](https://github.com/radareorg/r2ghidra/blob/master/dist/windows/r2pm/r2pm-i.ps1) downloads r2ghidra of version `5.8.2` which may be not compatible with r2 `6.x.x`
2. r2ghidra-6.x.x-w64.zip keeps missing since `6.0.2`

**Comment by trufae** [comment]
i hope i fixed the ci scripts properly now. i plan to release 6.1.4  this week

**Comment by huanceng** [comment]
after running the install command `r2pm -ci r2ghidra` with the latest 6.1.4 radare2, the `pdg` command still doesn't work

<img width="502" height="43" alt="Image" src="https://github.com/user-attachments/assets/4b771637-63cd-48ab-9209-ff78ae23fb48" />

**Comment by trufae** [comment]
Is the plugin listed when you do Lc? Any relevant log if you set R2_DEBUG=1 environ?

**Comment by huanceng** [comment]
1. not listed in Lc
2. no relevant log

<img width="734" height="271" alt="Image" src="https://github.com/user-attachments/assets/df142546-af74-4e7d-b51c-891491e915a3" />

**Comment by trufae** [comment]
The environment must be set before starting r2, if you see nothing its probably not loading the plugin. Try doing “L core_ghidra.dll”

**Comment by huanceng** [comment]
below is the log after `L core_ghidra.dll`

<img width="438" height="95" alt="Image" src="https://github.com/user-attachments/assets/3f645927-0632-46bd-802e-d99ffe8998e6" />

**Comment by huanceng** [comment]
some relevant logs are found at the beginning when starting r2

<img width="839" height="477" alt="Image" src="https://github.com/user-attachments/assets/012565ba-fb61-40d1-8b43-c2d5432009e8" />

**Comment by 4Freak** [comment]
W64 release `6.1.4`. After plugin installation (manual or by r2pm) r2 refuse to start

<img width="511" height="119" alt="Image" src="https://github.com/user-attachments/assets/1edf244a-4ac7-41ae-9f2d-58bfacf7c5d4" />\
Update: after manual compilation and get next error:
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 904
Expression: _CrtlsValidHeapPointer(block)

With next stack trace: 

<img width="886" height="344" alt="Image" src="https://github.com/user-attachments/assets/409d3f23-b2d7-46be-a0d1-c4986a0f91c2" />

**Comment by trufae** [comment]
Can someone verify and test latest 622?

**Comment by 4Freak** [comment]
W64 r2 - `6.2.2`.
r2ghidra successfully installed using r2pm
The environment variable `SLEIGHHOME` was not set automatically. After setting it manually everything works fine

**Comment by trufae** [comment]
Hopefully solved in https://github.com/radareorg/r2ghidra/pull/300 and we can finally call r2ghidra is perfection and 0 issues left to fix!!

**Comment by 4Freak** [comment]
It is solved. r2ghidra works without any additional tricks, thank you.

**Comment by trufae** [comment]
Closing! Thanks everyone for testing! Time to consolidate the current state with more tests so we dont break things in the future
